name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  publish-packages:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch ✔️
        uses: actions/checkout@v4

      - name: Set up Node.js 🛠️
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies 📦
        run: yarn install

      - name: Build packages 🧱
        run: yarn build:all

      - name: Prepare packages 🍔
        run: yarn prepare:all

      - name: Publish packages 🚊
        run: yarn publish:all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
